# Generated by Django 5.0.4 on 2024-04-22 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bwm', '0002_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkmessages',
            name='template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='bwm.templates'),
            preserve_default=False,
        ),
    ]
