# Generated by Django 5.0.4 on 2024-04-22 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bwm', '0003_bulkmessages_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkmessages',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bwm.templates'),
        ),
    ]
