# Generated by Django 5.0.4 on 2024-04-22 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bwm', '0004_alter_bulkmessages_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkmessages',
            name='template',
        ),
    ]
