# Generated by Django 5.0.4 on 2024-05-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bwm', '0007_messageresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageresponse',
            name='response',
            field=models.TextField(),
        ),
    ]
