# Generated by Django 5.0.4 on 2024-05-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bwm', '0008_alter_messageresponse_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageresponse',
            name='status',
            field=models.CharField(default='Failed', max_length=100),
        ),
    ]
