# Generated by Django 5.0.4 on 2024-05-22 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bwm', '0013_moneycounter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkmessages',
            name='image',
        ),
        migrations.AddField(
            model_name='bulkmessages',
            name='csv',
            field=models.FileField(blank=True, null=True, upload_to='bulk_message_csvs/'),
        ),
        migrations.AlterField(
            model_name='bulkmessages',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='bulk_messages/'),
        ),
    ]
